# Generated by Django 2.2.4 on 2019-09-01 18:20

import accounts.models
import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name=accounts.models.upload_image_path)),
                ('about', models.TextField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('realator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
