# Generated by Django 2.2.3 on 2019-08-01 02:09

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='properties.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyForSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('full_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('key_features', ckeditor.fields.RichTextField()),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('draf', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('location', models.CharField(max_length=200)),
                ('google_map', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.Category')),
                ('realator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('saved', models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(default='banglo', on_delete=django.db.models.deletion.DO_NOTHING, to='properties.Type')),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
