# Generated by Django 2.2 on 2019-07-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsell',
            name='property_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.Category'),
        ),
        migrations.AlterField(
            model_name='propertyforsell',
            name='property_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='properties.Category'),
        ),
    ]
