# Generated by Django 2.2 on 2019-07-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20190712_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyforsell',
            old_name='property_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='propertyforsell',
            old_name='property_type',
            new_name='type',
        ),
    ]
