# Generated by Django 2.2.3 on 2019-09-19 06:52

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import embed_video.fields
import phonenumber_field.modelfields
import places.fields
import sellproperty.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='sellproperty.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SellProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('full_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('key_features', ckeditor.fields.RichTextField()),
                ('min_price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('max_price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('draf', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('main_image', models.ImageField(default='default.jpg', upload_to=sellproperty.models.upload_image_path)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=sellproperty.models.upload_image_path)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=sellproperty.models.upload_image_path)),
                ('views', models.PositiveIntegerField(blank=True, default=0)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('action', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=6)),
                ('rent_per', models.CharField(blank=True, choices=[('nothing', 'One Time Price (For sale)'), ('month', 'MONTH (for rent)'), ('year', 'YEAR (for rent)')], max_length=30, null=True)),
                ('location', places.fields.PlacesField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellproperty.Category')),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('realator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellproperty.Type')),
            ],
            options={
                'ordering': ['-created'],
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MakeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=0, max_digits=3)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='make_offer', to='sellproperty.SellProperty')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('message', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry', to='sellproperty.SellProperty')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
