# Generated by Django 2.2.4 on 2019-09-01 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellproperty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproperty',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellproperty.Category'),
        ),
        migrations.AlterField(
            model_name='sellproperty',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellproperty.Type'),
        ),
    ]
