# Generated by Django 2.2.3 on 2019-09-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellproperty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproperty',
            name='rent_per',
            field=models.CharField(blank=True, choices=[('nothing', 'One Time Price (For sale)'), ('month', 'PER MONTH'), ('year', 'PER YEAR')], max_length=30, null=True),
        ),
    ]
