# Generated by Django 2.2.4 on 2019-09-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellproperty', '0004_auto_20190906_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-time']},
        ),
    ]
