# Generated by Django 2.2.4 on 2019-09-08 17:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sellproperty', '0005_auto_20190907_0540'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='enquiry',
            managers=[
                ('enquirycome', django.db.models.manager.Manager()),
            ],
        ),
    ]
