# Generated by Django 2.2.4 on 2019-09-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellproperty', '0006_auto_20190908_1724'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='enquiry',
            managers=[
            ],
        ),
    ]
