# Generated by Django 2.2.4 on 2019-09-10 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellproperty', '0007_auto_20190908_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproperty',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
