# Generated by Django 2.2.3 on 2019-09-13 20:21

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sellproperty', '0008_auto_20190910_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproperty',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
